### ISSUE TITLE
Support for Dark color theme needed.

### ISSUE THREAD

**Issue by beru** [HJLebbink/intrinsics-dude#1]
I can't read tooltip text well with Dark color theme.
![image](https://cloud.githubusercontent.com/assets/1131125/21586620/66a2176a-d116-11e6-9a54-2b344b5ed54e.png)

**Comment by HJLebbink** [comment]
I'll look into it

**Comment by beru** [comment]
I appreciate your help. :bow:

**Comment by HJLebbink** [comment]
Could you please check version 1.1.2.1 and confirm that it indeed renders the text readable.

**Comment by beru** [comment]
I need to setup Visual Studio 2015 SDK to build the installer, so please wait.

**Comment by HJLebbink** [comment]
The installer for version 1.1.2.1 can be downloaded from releases

**Comment by beru** [comment]
It looks like it's working fine with 1.1.2.1. Thank you! @HJLebbink 
![image](https://cloud.githubusercontent.com/assets/1131125/21592160/7bcd4046-d14e-11e6-8a05-83560e06e8e5.png)
