### ISSUE TITLE
Non-configurable color in tooltips

### ISSUE THREAD

**Issue by JohanKAdams** [HJLebbink/intrinsics-dude#2]
The tooltips use a bluish color for typenames (`void`, `float`, etc.). This color is not configurable, and the user ends up with hard to read text depending on the other color settings:

![tooltip-3](https://cloud.githubusercontent.com/assets/29004367/26529888/b9941602-43d1-11e7-938f-fc433b1ddebc.png)

**Comment by HJLebbink** [comment]
I agree. I wasn't too happy about the colouring in the tooltips, I'll remove the blue type info in the next version.
