### ISSUE TITLE
separate completion list is not working.

### ISSUE THREAD

**Issue by ZeeWanderer** [HJLebbink/intrinsics-dude#3]
![untitled](https://user-images.githubusercontent.com/8377469/36030613-965920ac-0db0-11e8-96e2-5a224949fa36.png)

**Comment by ZeeWanderer** [comment]
![untitled](https://user-images.githubusercontent.com/8377469/36030754-107c6100-0db1-11e8-9f64-b1053a647c20.png)

**Comment by HJLebbink** [comment]
Statement completion and the accompanying descriptions is by default not switched on.

I don't understand what is not working in "separate completion list is not working", could you explain.

**Comment by ZeeWanderer** [comment]
By ReadMe description, i thought that separate statement completion list for intrinsics is by default on. No issue.

**Comment by HJLebbink** [comment]
Yes I should mention that it is switched off by default, simply because most people don't want to be bothered by it in regular C/C++ coding.
