### ISSUE TITLE
Missing intrinsics?

### ISSUE THREAD

**Issue by human-0** [HJLebbink/intrinsics-dude#5]
Some intrinsics seem to be missing and unhighlighted, such as __popcnt/__popcnt64 and _byteswap_ulong/uint64 (although _mm_popcnt_u32/64 does work).

![image](https://user-images.githubusercontent.com/33237916/46576877-a40f5580-ca21-11e8-8cd6-e0aaa658433c.png)

EDIT: byteswap isn't actually and intrinsic but popcnt is still not working.

**Comment by HJLebbink** [comment]
Yes, visual studio compiler vs Intel compiler, several thing here.

Only the compiler intrinsics as defined by Intel are provided; they are scraped from [here](https://software.intel.com/sites/landingpage/IntrinsicsGuide/). Some of these intrinsics, such as those for endianness, have been around quite a while, and differ between compilers. I personally try to stick to what ICC provides me, but if you want to use VS compiler I guess you are out of luck.

Double underscore __ in identifiers is reserved for the compiler's internal use. The __popcnt* intrinsics are VS compiler specific, (although I can't find them in the VS2017 documentation). I would use __ only for compiler specific tests. 

the _byteswap_u* are defined in Microsoft's stdlib.h; the Intel alternatives (eg [_bswap](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=577,576&text=_bswap)) are in immintrin.h, but annoyingly not for the VS compiler.

I hope this helps.

**Comment by human-0** [comment]
Ok, that makes sense. It also explains why there is no __cpuid.
