### ISSUE TITLE
No parameter information with this extension enabled.

### ISSUE THREAD

**Issue by human-0** [HJLebbink/intrinsics-dude#6]
When this extension is enabled, normal visual studio IntelliSense does not show function parameters when writing the function call.

Without the extension:
![screenshot 22](https://user-images.githubusercontent.com/33237916/47262797-cf279800-d53d-11e8-861c-1437805cf26d.png)

With the extension:
![screenshot 21](https://user-images.githubusercontent.com/33237916/47262802-f1b9b100-d53d-11e8-8608-b376929d81a8.png)

EDIT: Turning off signature help does solve it without disabling the extension (which requires a VS restart). However, you don't get the improved signature help.

**Comment by HJLebbink** [comment]
Yep, took a while but this is fixed in a version after 1.2.1.0
